[package]
name = "jtf-platform-links"
description = "Creating a symbolic link, which has no portable API."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
jtf-core = { workspace = true }

[lints]
workspace = true
